language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: superkhau@gmail.com
  api_key:
    secure: jOpwk2nFjfSoe8lwm9hGcKvTI9p5VPPWK+oMNsrKIPeD1rGMbwRziVr1dbCQS8D4F7D7uh8mdTsMSyaxVgPZAaOzvHbiOB/RzhAgEhagQcNq0cixeUc5tb2zVD2HiTOsF10EjhYUx1QcM4vpFYQZiJBYuTeuanjY2UHNLJqPLuQfsuBcVWk0XZ7if14Onr3tfNeDs23DIHBB/42xVH+0zWiIR+0fmJzvsbBjeKyW3PcUT74bhw3WezRaP6Y0Dgjz4JOnIim/RBO7r5XlijSBX5MSrSIoQD5GNjgkeIPguaEGFC3hYtJrUVJ9rXR6aoh3zscr6shMxLLWzoAUu4MTFhYnm7XfymWb6c+Hhn1nPat5+bkBRhLOlWA6sOSeMK0MJeIUcxpCFeCymfNtOYD1X4G8X6ej8jnV3KN6R0TvjDvAIgoFB5XaQkrVjJ3KgFyIMMqhvGMZkrPTyoJGEhfRy3iQ1+TAR5K80L6QYvcDImeu+phz7wJC6nkmIDsmI3WchqQthh82Yq/QlZvdvAMRWY25dYT16WglMetT89OuqLWBA1jAsGzr6Q+3T4nZ2wD84SSpvDupB9RfwAffddoe/u7sQqerOoBnDwN55yiHPc3p+tBWO8FbPtbFeoJl+zCMrltJ9hbbuvpW11+gXCllbT7X93p0BD0OM7SokLRwxXM=
  on:
    repo: superkhau/sandbox
